fixed bugs

diff --git a/ass1/pigs-show b/ass1/pigs-show
--- a/ass1/pigs-show
+++ b/ass1/pigs-show
@@ -15,6 +15,7 @@ then
         fi
         exit 0
     done
+    echo "error: '$FileName' not found in index" 1>&2
 fi
 
 #Commit Num is included
@@ -23,7 +24,13 @@ do
     dirNum="$(echo $dir | cut -d'/' -f3)"
     if [ "$dirNum" = "$CommitNum" ]
     then
+        ShowFile=.pig/commits/"$CommitNum"/"$FileName"
+        if [ ! -f  "$ShowFile" ]
+        then
+            echo "error: $FileName not found in commit $CommitNum" 1>&2
+        fi
         cat .pig/commits/$CommitNum/$FileName
         exit 0
     fi
+    echo "error: unknown commit '$CommitNum'" 1>&2
 done
