Fixed subset0 bug

diff --git a/ass1/pigs-init b/ass1/pigs-init
--- a/ass1/pigs-init
+++ b/ass1/pigs-init
@@ -2,7 +2,7 @@
 
 if test -d .pig 
 then
-    echo "./pigs-init: error: .pig already exists" 1>&2
+    echo "pigs-init: error: .pig already exists" 1>&2
     exit 1
 fi
 
