Added error checks

diff --git a/ass1/pigs-add b/ass1/pigs-add
--- a/ass1/pigs-add
+++ b/ass1/pigs-add
@@ -1,6 +1,17 @@
 #!/bin/dash
 
+if [ ! -d .pig ] 
+then
+    echo "$0: error: pigs repository directory .pig not found" 1>&2
+    exit 1
+fi
+
 for file in "$@"
 do
+    if [ ! -f $file ] 
+    then
+        echo "$0: error: can not open '$file'" 1>&2
+        exit 1
+    fi
     cp "$file" .pig/index
 done
